#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is responsible for launching Chromium, monitoring it, and restarting after a certain period of inactivity.

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import os
import platform
import shlex
import shutil
import subprocess
import sys
import time

from toolbox.builder import TextBuilder
from toolbox.driver import KioskDriver
from toolbox.errors import CommandError, KioskError
from toolbox.invoke import invoke_text
from toolbox.kiosk import Kiosk
from toolbox.logger import Logger

KIOSKFORGE_TO_XRANDR_ROTATIONS = {
	'none'  : 'normal',
	'left'  : 'left',
	'flip'  : 'inverted',
	'right' : 'right'
}

class KioskOpenbox(KioskDriver):
	"""This class defines the KioskOpenbox.py script, which starts Chromium, monitors it, and restarts it if necessary."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	# Returns the total number of seconds (with a fraction) of idle time since the X server was last busy.
	@staticmethod
	def x_idle_time() -> float:
		result = invoke_text("xprintidle")
		if result.status != 0:
			raise KioskError("Unable to get idle time from X Windows")
		return int(result.output) / 1000

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if platform.system() != "Linux":
			raise KioskError("This script is can only be run on a Linux kiosk machine")

		# Parse command-line arguments.
		if len(arguments) != 0:
			raise CommandError('"KioskOpenbox.py"')

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Fetch timeout value (0 = disabled, other = number of seconds) from configuration file.
		timeout = kiosk.idle_timeout.data

		process = None
		try:
			# Disable all forms of X screen saver/screen blanking/power management.
			for xset in [ "xset s off", "xset s noblank", "xset -dpms"]:
				subprocess.check_call(shlex.split(xset), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
			del xset

			if kiosk.screen_rotation.data != "none":
				# Ask 'xrandr' to rotate the screen as per the `screen_rotation` setting.
				command  = TextBuilder()
				command += "xrandr"
				command += "--output"
				command += "HDMI-1"
				command += "--rotate"
				command += KIOSKFORGE_TO_XRANDR_ROTATIONS[kiosk.screen_rotation.data]
				subprocess.check_call(command.list, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
				del command

			# Build the Chromium command line with a horde of options (I don't know which ones work and which don't...).
			# NOTE: Chromium does not complain about any of the options listed below!
			command  = TextBuilder()
			command += shutil.which("chromium") or "chromium"
			command += "--kiosk"
			command += "--fast"
			command += "--fast-start"
			command += "--start-maximised"
			command += "--noerrdialogs"
			command += "--no-first-run"
			command += "--enable-pinch"
			command += "--overscroll-history-navigation=disabled"
			command += "--disable-features=TouchpadOverscrollHistoryNavigation"
			command += "--overscroll-history-navigation=0"
			command += "--disable-restore-session-state"
			command += "--disable-infobars"
			command += "--disable-crashpad"
			if kiosk.user_options.data:
				for option in shlex.split(kiosk.user_options.data):
					command += option
			command += kiosk.command.data
			cmdlist  = command.list
			del command

			# Forever launch Chromium, possibly terminate it, and restart it again if terminated or crashed.
			while True:
				# Launch Chromium in the background as a detached process.
				try:
					# pylint: disable-next=consider-using-with
					process = subprocess.Popen(cmdlist, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
				except subprocess.SubprocessError as that:
					raise KioskError("Unable to launch Chromium") from that
				except OSError as that:
					raise KioskError(that.strerror or "Unknown OS error") from that

				# Let Chromium start before we begin to check if it has been idle for too long.
				time.sleep(15)

				# Loop forever, launching Chromium and terminating it if it "times out" (becomes idle for N seconds).
				while True:
					# Wait one second between checking if Chromium should be restarted.
					time.sleep(1)

					# If Chromium has exited (crashed), exit to outer loop to restart it.
					if process.poll():
						logger.error("Restarting Chromium after crash.")
						break

					# If X has been idle for more than N seconds, terminate Chromium and exit to outer loop to restart it.
					if timeout and self.x_idle_time() >= timeout:
						process.terminate()
						process = None

						# Reset X's idle timer to ensure that inaccuracies do not accumulate over time.
						subprocess.check_call(shlex.split("xset s reset"), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

						break
		finally:
			# Terminate Chromium if it is still running.
			if process and not process.poll():
				process.terminate()
				del process


if __name__ == "__main__":
	app = KioskOpenbox()
	# pylint: disable-next=invalid-name
	code = app.main(sys.argv)
	sys.exit(code)
