#!/usr/bin/env python3

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import Any, Dict, List, Optional, TextIO, Tuple

import os
import platform
import shlex
import shutil
import subprocess
import sys
import time

from kiosk.builder import TextBuilder
from kiosk.errors import *
from kiosk.invoke import invoke
from kiosk.logger import Logger
import kiosk.KioskClass
from kiosk.setup import *
from kiosk.version import *


class KioskStart(kiosk.KioskClass.KioskClass):
	"""This class contains the 'KioskStart' code, which starts Chromium, monitors it, and restarts it if necessary."""

	def __init__(self) -> None:
		kiosk.KioskClass.KioskClass.__init__(self)
		self.version = Version("KioskStart", VERSION, COMPANY, CONTACT, TESTING)

	# Returns the total number of seconds (with a fraction) of idle time since the X server was last busy.
	@staticmethod
	def x_idle_time() -> float:
		result = invoke("xprintidle")
		if result.status != 0:
			raise KioskError("Unable to get idle time from X Windows")
		return int(result.output) / 1000

	# Discards all UTF-8 characters from the given string and returns the result.
	@staticmethod
	def utf8_discard(text : str) -> str:
		result = ""
		for ch in text:
			if ord(ch) >= 0x80:
				continue
			result += ch
		return result

	# NOTE: This function returns all xinput touch device ids but a few predefined ids.  I haven't found a better method just yet.
	@staticmethod
	def xinput_get_pointer_device_ids() -> List[str]:
		# Ask 'xinput' for a list of all known pointing and keyboard devices.
		result = invoke("xinput list")
		if result.status != 0:
			raise KioskError("Could not invoke 'xinput'")

		# Split the 'xinput' output into separate lines.
		lines = result.output.split("\n")

		# Remove lame embedded UTF-8 characters.
		lines = list(map(KioskStart.utf8_discard, lines))

		# Extract device ids for all relevant devices from the output of 'xinput list'.
		found = []
		store = False
		for line in lines:
			# Strip leading whitespace from each line.
			line = line.strip(" \t")

			# Locate device id or ignore the line if not found.
			id_pos = line.find('id=')
			if id_pos == -1:
				continue

			# Locate master/slave info or ignore line if not found.
			kind_pos = line.find('[')
			if kind_pos == -1:
				continue

			# Extract device name and id.
			(name, id) = (line[:id_pos].strip(), line[id_pos+3:kind_pos].strip())

			# Guard against unintentional uses of 'line' in the code below.
			del line

			if name == "Virtual core pointer":
				store = True
			elif name == "Virtual core keyboard":
				store = False
			elif name[:9] == "vc4-hdmi-":
				continue
			elif store:
				found.append(id)

		# Discard the 'Virtual core XTEST pointer' entry.
		#found = list(filter(lambda x: x != 'Virtual core XTEST pointer', found))

		return found

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if platform.system() != "Linux":
			raise KioskError("This script is can only be run on a Linux kiosk machine")

		# Parse command-line arguments.
		if len(arguments) != 0:
			raise SyntaxError('"KioskStart.py"')

		# Load settings generated by KioskForge on the desktop machine.
		setup = Setup()
		setup.load(origin + os.sep + "KioskForge.cfg")

		# Fetch timeout value (0 = disabled, other = number of seconds) from configuration file.
		timeout = setup.idle_timeout.data

		process = None
		try:
			# Disable all forms of X screen saver/screen blanking/power management.
			for xset in [ "xset s off", "xset s noblank", "xset -dpms"]:
				subprocess.check_call(shlex.split(xset), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
			del xset

			# Rotate the screen, if applicable.
			if setup.rotate_screen.data != 0:
				orientation = setup.rotate_screen.data

				# Ask 'xrandr' to rotate the screen.
				command  = TextBuilder()
				command += "xrandr"
				command += "--output"
				command += "HDMI-1"
				command += "--rotate"
				command += { 0 : 'normal', 1 : 'left', 2 : 'inverted', 3 : 'right' }[orientation]
				subprocess.check_call(command.list, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
				del command

				# Identify and configure all non-reserved pointing devices using 'xinput'.
				matrices = {
					0 : '1 0 0 0 1 0 0 0 1',
					1 : '0 -1 1 1 0 0 0 0 1',
					2 : '-1 0 1 0 -1 1 0 0 1',
					3 : '0 1 0 -1 0 1 0 0 1'
				}
				devices = self.xinput_get_pointer_device_ids()
				for device in devices:
					command  = TextBuilder()
					command += "xinput"
					command += "set-prop"
					command += "'%s'" % device
					command += "'Coordinate Transformation Matrix'"
					command += "'%s'" % matrices[orientation]
					# NOTE: Use 'subprocess.run()' to avoid having to check or process the possibly likely exit code from 'xinput'.
					# NOTE: I sort of brute-force attempt to configure all discovered pointing devices, so 'xinput' WILL fail.
					subprocess.run(command.list)
					del command

			# Build the Chromium command line with a horde of options (I don't know which ones work and which don't...).
			# NOTE: Chromium does not complain about any of the options listed below!
			command  = TextBuilder()
			command += shutil.which("chromium") or "chromium"
			command += "--kiosk"
			command += "--fast"
			command += "--fast-start"
			command += "--start-maximised"
			command += "--noerrdialogs"
			command += "--no-first-run"
			command += "--enable-pinch"
			command += "--overscroll-history-navigation=disabled"
			command += "--disable-features=TouchpadOverscrollHistoryNavigation"
			command += "--overscroll-history-navigation=0"
			command += "--disable-restore-session-state"
			command += "--disable-infobars"
			command += "--disable-crashpad"
			command += "%s" % setup.website.data
			cmdlist  = command.list
			del command

			# Forever launch Chromium, possibly terminate it, and restart it again if terminated or crashed.
			while True:
				# Launch Chromium in the background as a detached process.
				try:
					process = subprocess.Popen(cmdlist, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
				except subprocess.SubprocessError:
					raise KioskError("Unable to launch Chromium")
				except OSError as that:
					raise KioskError(that.strerror)

				# Let Chromium start before we begin to check if it has been idle for too long.
				time.sleep(15)

				# Loop forever, launching Chromium and terminating it if it "times out" (becomes idle for N seconds).
				while True:
					# Wait one second between checking if Chromium should be restarted.
					time.sleep(1)

					# If Chromium has exited (crashed), exit to outer loop to restart it.
					if process.poll():
						logger.error("Restarting Chromium after crash.")
						break

					# If X has been idle for more than N seconds, terminate Chromium and exit to outer loop to restart it.
					current = self.x_idle_time()
					if timeout and current >= timeout:
						process.terminate()
						process = None

						if TESTING:
							logger.write("Restarting Chromium after idle timeout: timeout=%f, current=%f." % (timeout, current))

						# Reset X's idle timer to ensure that inaccuracies do not accumulate over time.
						subprocess.check_call(shlex.split("xset s reset"), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

						break
		finally:
			# Terminate Chromium if it is still running.
			if process and not process.poll():
				process.terminate()


if __name__ == "__main__":
	app = KioskStart()
	code = app.main(sys.argv)
	sys.exit(code)

