#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is a tiny UDP broadcast discovery server, which allows us to discover all KioskForge kiosks on the LAN.

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import os
import sys
import socket

from kiosklib.discovery import COMMAND, SERVICE
from kiosklib.driver import KioskDriver
from kiosklib.errors import CommandError, KioskError
from kiosklib.kiosk import Kiosk
from kiosklib.logger import Logger
from kiosklib.network import internet_active, lan_broadcast_address, wait_for_internet_active
from kiosklib.signal import Signal


class KioskDiscoveryServer(KioskDriver):
	"""Defines the KioskDiscoveryServer class, starts an UDP broadcast server to allow KioskForge to discover kiosks on the LAN."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":		# pylint: disable=duplicate-code (duplicate-code)
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we haven't got root privileges.
		# pylint: disable-next=no-member
		if os.geteuid() != 0:			# pyrefly: ignore[missing-attribute]
			raise KioskError("You must be root to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:						# pylint: disable=duplicate-code
			raise CommandError('"KioskDiscoveryServer.py"')

		logger.write("Starting kiosk discovery service.")

		# Check that we have got an active, usable internet connection, otherwise wait for at most 60 seconds for it come up.
		if not internet_active():
			logger.write("*** NETWORK DOWN: Waiting indefinitely for the kiosk to come online")
			wait_for_internet_active()

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Create a shutdown signal watcher so that we can shut down if/when the kiosk is cleanly shut down.
		shutdown_signal = Signal("kiosk-shutdown", owner=kiosk.user_name.data)

		# Create an UDP socket.
		server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)

		try:
			# Bind the UDP socket to the broadcast address of the local LAN.
			server.bind((lan_broadcast_address(), SERVICE))

			while not shutdown_signal.exists:
				# Wait indefinitely for a command from a KioskForge client.
				(command, remote) = server.recvfrom(1024)
				if command == COMMAND:
					logger.write(f"({remote[0]}:{remote[1]}) Replying to valid request.")
					server.sendto(command, remote)
				else:
					logger.error(f"({remote[0]}:{remote[1]}) Ignoring invalid request.")

			logger.write("Shutting down kiosk discovery service.")
		finally:
			server.close()


if __name__ == "__main__":
	sys.exit(KioskDiscoveryServer().main(sys.argv))
