#!/usr/bin/env python3
#**********************************************************************************************************************************
# BSD 3-Clause License for KioskForge - https://kioskforge.org:
#
# Copyright © 2024-2025 The KioskForge Team.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#**********************************************************************************************************************************

# This script is responsible for upgrading KioskForge itself after someone has dumped 'KioskForge.zip' in the user's home folder.

import glob
import os
import sys
from typing import List

from kiosklib.driver import KioskDriver
from kiosklib.errors import CommandError, KioskError
from kiosklib.invoke import invoke_list_safe
from kiosklib.kiosk import Kiosk
from kiosklib.logger import Logger


class KioskUpgrade(KioskDriver):
	"""This class implements the KioskUpgrade.py script, which updates the KioskForge installation itself."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we've got root privileges.
		# pylint: disable-next=no-member
		if os.geteuid() != 0:			# pyrefly: ignore[missing-attribute]
			raise KioskError("You must be root to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:
			raise CommandError('"KioskUpgrade.py"')

		logger.write("Kiosk upgrader starting.")

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# If no KioskForge upgrade is available, simply exit this script again.
		if not os.path.isfile("/home/kiosk/KioskForge.zip"):
			return

		logger.write("KioskForge upgrade found so performing upgrade.")

		# TODO: Handle the case that a new .kiosk file was uploaded (not yet possible as KioskSetup.py needs to do its magic).

		# Make sure there's no new version of KioskForge from a failed earlier upgrade.
		invoke_list_safe(["rm", "-fr", "/home/kiosk/KioskForge.new"])

		# Unzip the upgrade into /home/kiosk/KioskForge.new before moving it into place as the current kiosk (~/KioskForge).
		invoke_list_safe(["sudo", "-u", "kiosk", "unzip", "/home/kiosk/KioskForge.zip", "-d", "/home/kiosk/KioskForge.new"])

		# Copy over the .kiosk file from the current kiosk to the new kiosk.
		invoke_list_safe(
			["sudo", "-u", "kiosk", "cp", "-p", "/home/kiosk/KioskForge" + os.sep + "KioskForge.kiosk", "/home/kiosk/KioskForge.new"]
		)

		# Change file permissions as ZIP doesn't store those.
		for file in ["/home/kiosk/KioskForge.new"] + glob.glob("/home/kiosk/KioskForge.new" + os.sep + "**"):
			(_, ext) = os.path.splitext(file)
			del _

			if os.path.isdir(file) or ext in [".py"]:
				invoke_list_safe(["chmod", "ug=rx,o=", file])
			elif ext in [".kiosk", ".md"]:
				invoke_list_safe(["chmod", "ug=r,o=", file])
			else:
				print(f"Warning: Skipping unknown file: {file}")

		# If an old version of KioskForge exists, remove it.
		invoke_list_safe(["rm", "-fr", "/home/kiosk/KioskForge.old"])

		# Save the current version of KioskForge for "easy" manual recovery, if the upgrade fails.
		os.rename("/home/kiosk/KioskForge", "/home/kiosk/KioskForge.old")

		# Move the new version of KioskForge into place.
		os.rename("/home/kiosk/KioskForge.new", "/home/kiosk/KioskForge")

		# Remove the upgrade archive so that we don't perform the upgrade again on the next boot and forever after until removed.
		invoke_list_safe(["rm", "-f", "/home/kiosk/KioskForge.zip"])

		logger.write("Kiosk upgrader rebooting after successfully upgrading KioskForge.")

		# Reboot the system so that the new KioskForge installation takes effect.
		invoke_list_safe(["reboot"])


if __name__ == "__main__":
	sys.exit(KioskUpgrade().main(sys.argv))
