#!/usr/bin/env python3
#**********************************************************************************************************************************
# BSD 3-Clause License for KioskForge - https://kioskforge.org:
#
# Copyright © 2024-2026 The KioskForge Team.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
#    in the documentation and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
# NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#**********************************************************************************************************************************
# This script is a tiny UDP broadcast discovery server, which allows us to discover all KioskForge kiosks on the LAN segment(s).
#
# NOTES:
#    1. The server does not implement support for the global KioskForge 'shutdown' signal as it blocks waiting for packets.
#    2. A better design than the above is sorely needed.  The server should (be) shut down when the kiosk shuts down.
#    3. The server is currently hard-coded to only accept /16 addresses on the current IPv4 LAN.  This must be fixed.

import os
import sys
import socket
from typing import List

from kiosklib.detect import pi_board_get
from kiosklib.discovery import COMMAND, SERVICE
from kiosklib.driver import KioskDriver
from kiosklib.errors import CommandError, KioskError
from kiosklib.kiosk import Kiosk
from kiosklib.logger import Logger
from kiosklib.network import lan_broadcast_address, wait_for_internet_active


class KioskDiscoveryServer(KioskDriver):
	"""Defines the KioskDiscoveryServer class, starts an UDP broadcast server to allow KioskForge to discover kiosks on the LAN."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":		# pylint: disable=duplicate-code (duplicate-code)
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we have got root privileges.
		# pylint: disable-next=no-member
		if os.geteuid() != 0:			# pyrefly: ignore[missing-attribute]
			raise KioskError("You must be root to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:						# pylint: disable=duplicate-code
			raise CommandError('"KioskDiscoveryServer.py"')

		logger.write("Starting kiosk discovery service.")

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Identify the Raspberry Pi board that we're running on.
		board = pi_board_get().replace(' ', '_')

		# Precompute the reply to speed up processing of incoming request a bit.
		reply = f"{COMMAND}: {kiosk.hostname.data}|{kiosk.version.version}|{kiosk.comment.data}|{board}".encode('utf-8')

		# Wait indefinitely until the internet is up.
		outer_loop = True
		while outer_loop:
			# TODO: Check if the kiosk is shutting down, in that case exit the loop by setting outer_loop to False and continue.

			# NOTE: This is mandatory as we detect our own LAN address by making a very short-lived broadcast server (see network.py).
			wait_for_internet_active()

			# Create an UDP socket.
			server = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
			try:
				# Bind the UDP socket to the broadcast address of the local LAN.
				server.bind((lan_broadcast_address(), SERVICE))

				inner_loop = True
				while inner_loop:
					# Wait indefinitely for a message from a KioskForge client.
					(message, remote) = server.recvfrom(1024)

					# If nothing was received, the exit the inner loop.
					if not message:
						inner_loop = False
						continue

					# Convert the message from bytes into UTF-8.
					# NOTE: Silence Pyrefly warning about 'command' possibly being uninitialized (it is not ever uninitialized!)
					command = ""
					try:
						command = message.decode('utf-8')
					except UnicodeDecodeError:
						logger.error(f"({remote[0]}:{remote[1]}) Ignoring malformed request.")
						continue
					del message

					# Ignore invalid commands.
					if command != COMMAND:
						logger.error(f"({remote[0]}:{remote[1]}) Ignoring invalid request.")
						continue

					# Reply to valid command.
					logger.write(f"({remote[0]}:{remote[1]}) Replying to valid request.")
					try:
						server.sendto(reply, remote)
					except OSError as that:
						# If the network went down, exit the inner loop and wait for it to come up again.
						logger.error(f"({remote[0]}:{remote[1]}) Error {that.errno}: {that.strerror}")
						inner_loop = False
						continue
			finally:
				server.close()

		logger.write("Stopping kiosk discovery service.")

if __name__ == "__main__":
	sys.exit(KioskDiscoveryServer().main(sys.argv))
