#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is responsible for updating, upgrading, and cleaning the system (only if there is an active internet connection).

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import os
import sys

from toolbox.actions import AptAction
from toolbox.driver import KioskDriver
from toolbox.errors import CommandError, KioskError
from toolbox.internet import internet_active
from toolbox.logger import Logger
from toolbox.invoke import invoke_text_safe
from toolbox.setup import Setup
from toolbox.version import Version


class KioskUpdate(KioskDriver):
	"""This class implements the KioskUpdate.py script, which updates the system if and only if it is on the internet."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)
		self.version = Version(self.project)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":
			raise KioskError("This script is can only be run on a Linux kiosk machine")

		# Check that we've got root privileges.
		if os.geteuid() != 0:		# pylint: disable=E1101
			raise KioskError("You must be root (use 'sudo') to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:						# pylint: disable=duplicate-code
			raise CommandError('"KioskUpdate.py"')

		# Load settings generated by KioskForge on the desktop machine.
		setup = Setup()
		setup.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# ******************** Perform tasks that do require an internet connection. *********************************************

		if not internet_active():
			logger.write("Not connected to the internet: Skipping system update, upgrade, and cleanup tasks.")
			return

		# Upgrade snaps and clean out the snap cache.
		try:
			# Allow snap to update (don't know if this is necessary or not, but err on the side of caution).
			invoke_text_safe("snap refresh --unhold")

			# Refresh all snaps.
			invoke_text_safe("snap refresh")

			# Purge the snap cache, this may grow to 5+ gigabytes over time.
			invoke_text_safe("rm -fr /var/lib/snapd/cache/*")
		finally:
			# Stop snapd from upgrading automatically (also done in 'KioskSetup.py').
			invoke_text_safe("snap refresh --hold")

		# Update apt package indices, upgrade all packages, and clean the apt cache (which may grow to many gigabytes in size).
		# NOTE: Use 'AptAction' to get automatic waiting for the 'apt' lock file to be released.
		# NOTE: Use "apt-get upgrade -y", not "apt-get dist-upgrade -y", to ensure that the system doesn't suddenly break down.
		for command in ["apt-get update", "apt-get upgrade -y", "apt-get clean"]:
			result = AptAction(f"Apt maintenance: {command}.", command).execute()
			if result.status != 0:
				logger.error(f"Apt failure executing '{command}': {result.output}")
			del result
		del command

		logger.write("Successfully updated and upgraded system.  Rebooting!")

		invoke_text_safe("reboot")


if __name__ == "__main__":
	sys.exit(KioskUpdate().main(sys.argv))

