#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is used to start the kiosk by configuring sound (if applicable), loading X11 or the user's app, etc.

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import os
import sys

from toolbox.builder import TextBuilder
from toolbox.driver import KioskDriver
from toolbox.errors import CommandError, KioskError
from toolbox.invoke import invoke_list_safe, invoke_text_safe
from toolbox.kiosk import Kiosk
from toolbox.logger import Logger
from toolbox.signal import Signal
from toolbox.various import screen_clear


class KioskStart(KioskDriver):
	"""Defines the KioskStart class, which is responsible for starting up the kiosk on every boot after it has been forged."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we don't have root privileges.
		# pylint: disable-next=no-member
		if os.geteuid() == 0:			# pyrefly: ignore[missing-attribute]
			raise KioskError("You may not be root when running this script")

		# Parse command-line arguments.
		if len(arguments) != 0:						# pylint: disable=duplicate-code
			raise CommandError('"KioskStart.py"')

		# Simply quit immediately, if the user is using an SSH connection.
		if "SSH_CONNECTION" in os.environ:
			return

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Disallow redundant launches of this script (there can only be ONE instance ;-)).
		signal = Signal("kiosk-running", owner=kiosk.user_name.data)
		if signal.exists:
			raise KioskError("Only one instance of this script can be running at any time.")

		try:
			# Create the signal that prevents this script from being launched multiple times thus running concurrently.
			signal.create()

			# Move ~/.xsession-errors to ~/.xsession-errors.old to avoid having it grow indefinitely forever.
			if os.path.isfile("~/.xsession-errors"):
				os.replace("~/.xsession-errors", "~/.xsession-errors.old")

			if kiosk.type.data in [ "x11", "web" ]:
				# Only execute the request if $DISPLAY is undefined and $XDG_VTNR is equal to 1 (avoid starting X11 twice).
				if not os.environ.get("DISPLAY") and os.environ.get("XDG_VTNR") == "1":
					# Launch X11, which runs '.config/openbox/autostart', which launches Chromium or the user app in kiosk mode.
					words  = TextBuilder()
					words += "startx"
					if not kiosk.mouse.data:
						words += "--"
						words += "-nocursor"
					invoke_list_safe(words.list)
			elif kiosk.type.data == "web-wayland":
				# TODO: Add support for the 'mouse' option (https://gist.github.com/seffs/2395ca640d6d8d8228a19a9995418211).
				if not os.environ.get("WAYLAND_DISPLAY"):
					invoke_text_safe("/usr/bin/dbus-update-activation-environment --systemd WAYLAND_DISPLAY=wayland-0")
					invoke_text_safe("/snap/bin/ubuntu-frame")
					invoke_text_safe(f"/snap/bin/chromium --kiosk '{kiosk.command.data}'")
			elif kiosk.type.data == "cli":
				invoke_text_safe(kiosk.command.data)
			else:
				raise KioskError(f"Unknown kiosk type: {kiosk.type.data}")

			screen_clear()
		finally:
			signal.remove()


if __name__ == "__main__":
	sys.exit(KioskStart().main(sys.argv))
