#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is responsible for updating, upgrading, and cleaning the system (only if there is an active internet connection).

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import glob
import os
import sys
import time

from toolbox.actions import AptAction
from toolbox.driver import KioskDriver
from toolbox.errors import CommandError, KioskError
from toolbox.invoke import invoke_text, invoke_text_safe
from toolbox.kiosk import Kiosk
from toolbox.logger import Logger
from toolbox.network import internet_active
from toolbox.signal import Signal


class KioskUpdate(KioskDriver):
	"""This class implements the KioskUpdate.py script, which updates the system if and only if it is on the internet."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def snap_cleanup(self, logger : Logger) -> None:
		"""Removes all revisions of snaps to keep disk usage to the bare minimum."""
		result = invoke_text("snap list --all --color=never --unicode=never")
		if result.status != 0:
			raise KioskError("Unable to get list of all snaps in system")

		# Split the output of 'snap list --all' into lines
		lines = result.output.strip().split(os.linesep)
		del result

		# Parse each line into six fields and remove all revisions of disabled snaps.
		# NOTE: Logic borrowed from https://www.debugpoint.com/clean-up-snap/
		for line in lines[1:]:
			(name, version, revision, tracking, publisher, notes) = line.split()
			del version
			del tracking
			del publisher

			# The 'notes' field is a comma-separated list of flags, parse them.
			flags = notes.split(",")
			del notes

			# We're only interested in disabled snaps - the rest are used by the system.
			if "disabled" not in flags:
				continue

			# Remove the old revision of the current snap.
			logger.write(f"Removing old snap revision {revision} of snap {name}")
			invoke_text_safe(f'snap remove "{name}" --revision="{revision}"')

		# Empty the snap cache, this may grow to many gigabytes over time.
		for file in glob.glob("/var/lib/snapd/cache/*"):
			os.unlink(file)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we've got root privileges.
		if os.geteuid() != 0:   		# pylint: disable=E1101
			raise KioskError("You must be root (use 'sudo') to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:			# pylint: disable=duplicate-code
			raise CommandError('"KioskUpdate.py"')

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Vacuum system logs every time we maintain the system if a maximum log size has been specified.
		if kiosk.vacuum_size.data != 0:
			invoke_text_safe(f"/usr/bin/journalctl --vacuum-size={kiosk.vacuum_size.data}M")

		# Not all kiosks are online so we need to handle the case that there's no internet gracefully.
		if internet_active():
			# Upgrade snaps and clean out the snap cache.

			# Stop Chromium and automatic respawns of it by creating a signal, which is watched for by 'KioskOpenbox.py'.
			signal = Signal("KioskOpenbox-shutdown-Chromium", kiosk.user_name.data)
			signal.create()
			logger.write("Signaled KioskOpenbox.py to shut down Chromium and then exit.")

			# Wait for KioskOpenbox.py to shut down, which means waiting until the signal has been removed.
			while signal.exists:
				time.sleep(1)
			logger.write("KioskOpenbox.py has shut down Chromium and exited.")
			del signal

			# NOTE: We don't start Chromium using 'snap run chromium', so don't use 'snap stop chromium'.
			# invoke_text_safe("snap stop chromium")

			# Stop X11 using "killall", the only way we have (we cannot kill the Python interpreter running this script...).
			invoke_text_safe("killall Xorg")

			# Ask snap to upgrade (refresh) all snaps.
			try:
				# Allow snap to update.
				invoke_text_safe("snap refresh --unhold")

				# Refresh all snaps.
				invoke_text_safe("snap refresh")
			finally:
				# Stop snapd from upgrading automatically so it doesn't upgrade randomly (done first in 'KioskSetup.py').
				invoke_text_safe("snap refresh --hold")

			# Remove all disabled snaps (prior snap versions) and empty the snap cache.
			self.snap_cleanup(logger)

			# Update apt package indices, upgrade all packages, and clean the apt cache (which may grow to many gigabytes in size).
			# NOTE: Use 'AptAction' to get automatic waiting for the 'apt' lock file to be released.
			# NOTE: We purge unused packages PRIOR to updating to ensure we've rebooted before doing this so as to not accidentally
			# NOTE: purge a running kernel, which may have catastrophic consequences as far as I know.
			# NOTE: Use "apt upgrade -y", not "apt-get dist-upgrade -y", to ensure that the system doesn't suddenly break down.
			# NOTE: Use "apt upgrade -y", not "apt-get upgrade -y", because "apt-get" doesn't install new packages (incl. kernels).
			for command in ["apt-get autoremove --purge", "apt-get update", "apt upgrade -y", "apt-get clean"]:
				result = AptAction(f"Apt maintenance: {command}.", command).execute()
				if result.status != 0:
					logger.error(f"Apt failure executing '{command}': {result.output}")
				del result

			logger.write("Successfully cleaned, purged, vacuumed, updated, and upgraded system.")

		# Execute the requested post-upgrade action.
		match kiosk.upgrade_post.data:
			case "reboot":
				invoke_text_safe("reboot")
			case "poweroff":
				invoke_text_safe("poweroff")
			case _:
				raise KioskError(f"Invalid value in 'upgrade_post' option: {kiosk.upgrade_post.data}")


if __name__ == "__main__":
	sys.exit(KioskUpdate().main(sys.argv))
