#!/usr/bin/env python3
# KioskForge - https://kioskforge.org
# Copyright (c) 2024-2025 Vendsyssel Historiske Museum (me@vhm.dk). All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following
# conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice, this list of conditions and the disclaimer below.
#     * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided with the distribution.
#     * Neither the name of Vendsyssel Historiske Museum nor the names of its contributors may be used to endorse or promote
#       products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# This script is used to configure various things that need root privileges to configure such as the 'wifi_boost' field.

# Import Python v3.x's type hints as these are used extensively in order to allow MyPy to perform static checks on the code.
from typing import List

import os
import sys

from kiosklib.driver import KioskDriver
from kiosklib.errors import CommandError, KioskError
from kiosklib.kiosk import Kiosk
from kiosklib.logger import Logger
from kiosklib.network import wifi_boost

class KioskConfig(KioskDriver):
	"""Defines the KioskConfig class, which is responsible for configuring the system as root (invoked from 'rc.local')."""

	def __init__(self) -> None:
		KioskDriver.__init__(self)

	def _main(self, logger : Logger, origin : str, arguments : List[str]) -> None:
		# Check that we're running on Linux.
		if sys.platform != "linux":		# pylint: disable=duplicate-code (duplicate-code)
			raise KioskError("This script can only be run on a Linux kiosk machine")

		# Check that we've got root privileges.
		# pylint: disable-next=no-member
		if os.geteuid() != 0:		# pyrefly: ignore[missing-attribute]
			raise KioskError("You must be root to run this script")

		# Parse command-line arguments.
		if len(arguments) != 0:						# pylint: disable=duplicate-code
			raise CommandError('"KioskConfig.py"')

		logger.write("Starting kiosk configurator.")

		# Load settings generated by KioskForge on the desktop machine.
		kiosk = Kiosk(self.version)
		kiosk.load_safe(logger, origin + os.sep + "KioskForge.kiosk")

		# Assign Wi-Fi power saving state (on or off), if applicable (if the wireless network has been enabled).
		if kiosk.wifi_name.data and kiosk.wifi_boost.data:
			logger.write("Boosting Wi-Fi by disabling power-saving mode.")
			wifi_boost(kiosk.wifi_boost.data)

		logger.write("Shutting down kiosk configurator.")


if __name__ == "__main__":
	sys.exit(KioskConfig().main(sys.argv))
