[project]
name = "KioskForge"
version = "1.02.0"
description = "KioskForge generates Raspberry Pi kiosks on top of Ubuntu Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ast-serialize==0.11.1",
    "bcrypt==5.0.0",
    "mypy==2.3.1",
    "pefile==2023.2.7",
    "pyinstaller==6.22.3",
    "pyinstaller-versionfile==3.1.0",
    "pylint==4.0.8",
    "pyrefly==1.3.0",
]
